#!/usr/bin/env bash
#
# Update dependencies mac via CLI.

set -o pipefail
set -o nounset

fancy_echo() {
	echo
	echo "==> $1"
	echo
}

# Check if command exists in path and is executable,
# otherwise skip.
entrypoint() {
	local -r cmd="$1"

	# shellcheck disable=2086
	if [ -x "$(command -v $cmd)" ]; then
		fancy_echo "$cmd up"
		return
	fi

	fancy_echo "Skipping $cmd"

	return 1
}

brew_up() {
	entrypoint brew || return

	brew update && brew upgrade && brew cleanup
	fancy_echo "brew cask up"
	brew cask upgrade --greedy
}

npm_up() {
	entrypoint npm || return

	npm update -g
}

yarn_up() {
	entrypoint yarn || return

	cd "$(yarn global dir)" &&
		yarn cache --force clean &&
		rm -rf node_modules/ &&
		yarn install &&
		yarn upgrade &&
		yarn autoclean --force
}

mas_up() {
	entrypoint mas || return

	mas upgrade
}

fisher_up() {
	entrypoint fish || return

	fish -c "fisher self-update"
}

gem_up() {
	entrypoint gem || return

	gem update --user-install
}

rcup_up() {
	entrypoint rcup || return

	rcup
}

tldr_up() {
	entrypoint tldr || return

	tldr --update
}

# VSCode
# Coming soon...
# https://github.com/Microsoft/vscode/issues/16459

main() {
	brew_up
	npm_up
	yarn_up
	mas_up
	fisher_up
	gem_up
	rcup_up
	tldr_up
	fancy_echo "Hooray! Everything up-to-date." && exit 0
}

main "$@"
